# -*- coding: utf-8 -*-
"""task6.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QgSWy2BeufBmzXIZHxDCTl4-htNT73Xv
"""

# Task 6: House Price Prediction

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

# Load dataset (use Kaggle house price dataset)
df = pd.read_csv("house_data.csv")

# Select features
X = df[["sqft_living", "bedrooms", "bathrooms"]]
y = df["price"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train model
model = LinearRegression()
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Evaluation
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("MAE:", mae)
print("RMSE:", rmse)

# Visualization
plt.scatter(y_test, y_pred)
plt.xlabel("Actual Prices")
plt.ylabel("Predicted Prices")
plt.title("Actual vs Predicted House Prices")
plt.show()