# -*- coding: utf-8 -*-
"""task1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QgSWy2BeufBmzXIZHxDCTl4-htNT73Xv
"""

# Task 1: Iris Dataset Exploration & Visualization

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load dataset
df = sns.load_dataset("iris")

# Basic inspection
print("Shape:", df.shape)
print("Columns:", df.columns)
print(df.head())

# Dataset info
df.info()

# Statistical summary
df.describe()

# Scatter plot
sns.scatterplot(data=df, x="sepal_length", y="sepal_width", hue="species")
plt.title("Sepal Length vs Sepal Width")
plt.show()

# Histograms
df.hist(figsize=(10,8))
plt.suptitle("Feature Distributions")
plt.show()

# Box plots
plt.figure(figsize=(10,6))
sns.boxplot(data=df)
plt.title("Box Plot to Identify Outliers")
plt.show()